from typing import Any, TextIO

from django.core.management.base import BaseCommand as BaseCommandOriginal
from tqdm import tqdm

class OutputBase:
    def error(self, text: str, ending: str = ..., fatal: bool = ...) -> None: ...
    def info(self, text: str, ending: str = ..., fatal: bool = ...) -> None: ...

class Tqdm(tqdm, OutputBase):
    command: BaseCommand
    isatty: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def write(
        self, text: str, file: TextIO = ..., ending: str = ..., fatal: bool = ..., error: bool = ...
    ) -> None: ...

class BaseCommand(BaseCommandOriginal, OutputBase):
    def write(self, text: str, ending: str = ..., fatal: bool = ..., error: bool = ...) -> None: ...
    def tqdm(self, *args: Any, **kwargs: Any) -> Tqdm: ...
